version: '3.2'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root2009
    ports:
      - '3306:3306'
    restart: unless-stopped
  imgapichn:
    image: d3nisovalle/imgapichn:v1
    ports:
      - '8080:8080'
  imgfrontchn:
    image: d3nisovalle/imgfrontchn:v1
    ports:
      - '3000:3000'